// Knowledge-graph ontology for the Aniimo QnA agent ("llm_wiki").
//
// The graph is built by ingesting the repo's structured data (data/research/*)
// into typed nodes + edges. Every node/edge carries provenance (confidence +
// sources) so the QnA agent can ground answers, cite them, and honestly say
// "unknown" instead of inventing — matching this wiki's no-invent policy.

export type Locale = "ko" | "en";

/** Cross-cutting trust tag carried by every node and edge. */
export type Confidence = "confirmed" | "marketing" | "community" | "unknown";

export type LocalizedText = { ko: string; en: string };

/** A branch of the category taxonomy the graph is organized under. */
export type Category = {
  id: string;
  label: LocalizedText;
  description: LocalizedText;
  /** Repo data files that feed this category during ingestion. */
  sources: string[];
  /** Node types that live under this category. */
  nodeTypes: NodeType[];
  children?: Category[];
};

/** Entity (node) kinds in the graph. */
export type NodeType =
  | "Game"
  | "Continent"
  | "Region"
  | "Biome"
  | "Weather"
  | "Creature"
  | "Form"
  | "Element"
  | "Role"
  | "Stage"
  | "StatBlock"
  | "System"
  | "Mechanic"
  | "Item"
  | "TrainingAction"
  | "EggType"
  | "MarkerType"
  | "Quest"
  | "Event"
  | "Reward"
  | "NamingPair"
  | "VersionNote"
  | "CommunityPost"
  | "Source";

/** Relationship (edge) kinds, with the node types they connect. */
export type EdgeType = {
  type: string;
  from: NodeType;
  to: NodeType;
  label: LocalizedText;
};

// ---------------------------------------------------------------------------
// 1. Category taxonomy (the structure the graph is organized under)
//
// Depth 1–2 are FIXED (owner decision 2026-09-30): one game root with ten
// sub-categories. Depth 3+ is AUTO-GENERATED by scripts/build-graph.mjs from
// node attributes (e.g. game.creature.lightning from the element field,
// game.egg.<kind> from egg data). "meta" stays a second root for wiki
// provenance plumbing (sources, naming, versions).
// ---------------------------------------------------------------------------

export const CATEGORY_TAXONOMY: Category[] = [
  {
    id: "game",
    label: { ko: "애니모 게임", en: "Aniimo Game" },
    description: { ko: "게임 콘텐츠 전반 — 지역·애니모·퀘스트·이벤트·스토리·파티·속성·아이템·무기·알", en: "All game content — regions, creatures, quests, events, story, party, elements, items, weapons, eggs" },
    sources: ["data/research/*.json"],
    nodeTypes: ["Game", "Region", "Creature", "Quest", "Event", "Element", "Item", "EggType", "CommunityPost", "Source"],
    children: [
      { id: "game.region", label: { ko: "지역", en: "Region" }, description: { ko: "에이델 대륙의 지역·서식지·바이옴", en: "Regions, habitats and biomes of Idyll" }, sources: ["data/research/regions.json"], nodeTypes: ["Region", "Continent"] },
      { id: "game.creature", label: { ko: "애니모", en: "Aniimo" }, description: { ko: "종·형태·종족치·진화 (하위: 속성별 자동 분류)", en: "Species, forms, stats, evolution (auto sub-split by element)" }, sources: ["data/research/creatures.json"], nodeTypes: ["Creature"] },
      { id: "game.quest", label: { ko: "퀘스트", en: "Quest" }, description: { ko: "메인/월드/돌발 퀘스트", en: "Main, world and dynamic quests" }, sources: ["data/research/wiki-outline.md"], nodeTypes: ["Quest", "CommunityPost"] },
      { id: "game.event", label: { ko: "이벤트", en: "Event" }, description: { ko: "한정 이벤트·시즌·콜라보·사전예약", en: "Limited-time events, seasons, collabs, pre-registration" }, sources: ["data/research/meta.json"], nodeTypes: ["Event", "CommunityPost"] },
      { id: "game.story", label: { ko: "스토리", en: "Story" }, description: { ko: "메인 스토리·설정·보스 진행 (미분류 게임 콘텐츠 포함)", en: "Main story, lore, boss progression (incl. uncategorized game content)" }, sources: ["data/research/world.md"], nodeTypes: ["Quest", "CommunityPost"] },
      { id: "game.party", label: { ko: "파티", en: "Party" }, description: { ko: "파티 조합·추천 덱·역할 시너지", en: "Party compositions, recommended teams, role synergies" }, sources: ["data/research/community.json"], nodeTypes: ["CommunityPost", "Creature"] },
      { id: "game.element", label: { ko: "속성", en: "Element" }, description: { ko: "9속성과 상성", en: "The nine elements and matchups" }, sources: ["data/research/creatures.json"], nodeTypes: ["Element"] },
      { id: "game.item", label: { ko: "아이템", en: "Item" }, description: { ko: "재료·도구·포획구 (하위: 종류별 자동 분류)", en: "Materials, tools, capture pods (auto sub-split by kind)" }, sources: ["data/research/training-sim-schema.json"], nodeTypes: ["Item"] },
      { id: "game.weapon", label: { ko: "무기", en: "Weapon" }, description: { ko: "무기 (데이터 미확보 시 비어 있음)", en: "Weapons (empty until verified data exists)" }, sources: [], nodeTypes: ["Item"] },
      { id: "game.egg", label: { ko: "알", en: "Egg" }, description: { ko: "알 종류·부화·교배 (하위: 종류별 자동 분류)", en: "Egg types, hatching, breeding (auto sub-split by kind)" }, sources: ["data/research/training-sim-schema.json"], nodeTypes: ["EggType", "Item"] },
    ],
  },
  {
    id: "meta",
    label: { ko: "위키 메타", en: "Wiki Meta" },
    description: { ko: "출처·표기·버전 등 위키 운영 정보", en: "Provenance, naming and version notes for wiki operations" },
    sources: ["data/research/sources.json", "data/research/meta.json"],
    nodeTypes: ["NamingPair", "Source", "VersionNote"],
    children: [
      { id: "meta.source", label: { ko: "출처", en: "Source" }, description: { ko: "인용 URL·접속일·유형", en: "Citation URLs, accessed date, type" }, sources: ["data/research/sources.json"], nodeTypes: ["Source"] },
      { id: "meta.naming", label: { ko: "표기 · 로컬라이제이션", en: "Naming · localization" }, description: { ko: "KO/EN 쌍·모호성(에이델=Idyll 등)", en: "KO/EN pairs, ambiguities (Idyll = 에이델, etc.)" }, sources: ["data/research/meta.json", "data/research/creatures.json"], nodeTypes: ["NamingPair"] },
      { id: "meta.version", label: { ko: "버전 기록", en: "Version notes" }, description: { ko: "패치·데이터 리비전", en: "Patches, data revisions" }, sources: ["data/research/meta.json"], nodeTypes: ["VersionNote"] },
    ],
  },
];

// ---------------------------------------------------------------------------
// 2. Relationships (edges)
// ---------------------------------------------------------------------------

export const EDGE_TYPES: EdgeType[] = [
  { type: "HAS_ELEMENT", from: "Creature", to: "Element", label: { ko: "속성", en: "has element" } },
  { type: "HAS_ROLE", from: "Creature", to: "Role", label: { ko: "역할", en: "has role" } },
  { type: "AT_STAGE", from: "Creature", to: "Stage", label: { ko: "진화 단계", en: "at stage" } },
  { type: "HAS_STATS", from: "Creature", to: "StatBlock", label: { ko: "종족치", en: "has stats" } },
  { type: "HAS_FORM", from: "Creature", to: "Form", label: { ko: "형태", en: "has form" } },
  { type: "EVOLVES_TO", from: "Creature", to: "Creature", label: { ko: "진화", en: "evolves to" } },
  { type: "FOUND_IN", from: "Creature", to: "Region", label: { ko: "서식지", en: "found in" } },
  { type: "PART_OF", from: "Region", to: "Continent", label: { ko: "소속 대륙", en: "part of" } },
  { type: "HAS_BIOME", from: "Region", to: "Biome", label: { ko: "바이오메", en: "has biome" } },
  { type: "HAS_WEATHER", from: "Region", to: "Weather", label: { ko: "날씨", en: "has weather" } },
  { type: "USES_ITEM", from: "Game", to: "Item", label: { ko: "게임 아이템", en: "uses item" } },
  { type: "AFFECTS", from: "System", to: "Creature", label: { ko: "영향", en: "affects" } },
  { type: "CONSUMES", from: "TrainingAction", to: "Item", label: { ko: "소비", en: "consumes" } },
  { type: "STRONG_AGAINST", from: "Element", to: "Element", label: { ko: "상성 우위(미확인)", en: "strong against (unknown)" } },
  { type: "REWARDS", from: "Quest", to: "Reward", label: { ko: "보상", en: "rewards" } },
  { type: "EVENT_REWARDS", from: "Event", to: "Reward", label: { ko: "이벤트 보상", en: "event rewards" } },
  { type: "TAKES_PLACE_IN", from: "Quest", to: "Region", label: { ko: "진행 지역", en: "takes place in" } },
  { type: "FEATURES", from: "Event", to: "Creature", label: { ko: "등장 애니모", en: "features" } },
  { type: "GRANTS_ITEM", from: "Reward", to: "Item", label: { ko: "지급 아이템", en: "grants item" } },
  { type: "GRANTS_CREATURE", from: "Reward", to: "Creature", label: { ko: "지급 애니모", en: "grants creature" } },
  // Provenance edges — attachable from ANY node.
  { type: "CITES", from: "Creature", to: "Source", label: { ko: "출처", en: "cites" } },
  { type: "HAS_NAMING", from: "Creature", to: "NamingPair", label: { ko: "표기", en: "has naming" } },
  // Community-post → entity linkage (fixes dangling post nodes in the graph).
  { type: "MENTIONS", from: "CommunityPost", to: "Creature", label: { ko: "언급", en: "mentions" } },
];

// ---------------------------------------------------------------------------
// 3. Cross-cutting properties present on EVERY node and edge
// ---------------------------------------------------------------------------

export const CROSS_CUTTING_PROPERTIES = {
  /** confirmed | marketing | community | unknown — drives honest answers. */
  confidence: "Confidence",
  /** Source node ids backing the fact (for citations). */
  sources: "Source[]",
  /** Bilingual display names. */
  names: "{ ko?: string; en?: string }",
  /** Data-pack date / last verification. */
  lastVerified: "ISO date string",
} as const;

/**
 * Answering policy for the QnA agent:
 * - Only answer from graph facts; never invent coordinates, stats, or names.
 * - Always surface the fact's `confidence` and cite `sources`.
 * - If confidence is "unknown" or no node/edge matches, answer "미확인 / unknown"
 *   and point to the official source link instead of guessing.
 */
export const ANSWER_POLICY = {
  groundedOnly: true,
  requireCitations: true,
  unknownFallback: true,
} as const;
